using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.WPF.Reflection.Attributes;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using ICSharpCode.SharpZipLib;

namespace ApothecaryAutoPatcher
{
/// <summary>
/// A record to hold the effect data for each ingredient. This is used to override the effects of the ingredients in the patcher.
/// </summary>
/// <param name="BaseEffect">The base effect of the ingredient.</param>
/// <param name="Magnitude">The magnitude of the effect.</param>
/// <param name="Duration">The duration of the effect.</param>
/// <remarks>This record is used to store the effect data for each ingredient. It is used to override the effects of the ingredients in the patcher.</remarks>
/// <example>
/// var effect = new Effect(Skyrim.MagicEffect.AlchRestoreHealth, 0.96f, 10);
/// </example>

    public class Program
    {
        static Lazy<Settings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "ApothecaryAutoPatcher.esp")
                .Run(args);
        }

        /// <summary>
        /// The main patching method. This method is called by the Synthesis pipeline to run the patcher.
        /// </summary>
        /// <param name="state">The state of the patcher.</param>
        /// <remarks>This method is called by the Synthesis pipeline to run the patcher. It is responsible for patching the ingredients in the load order.</remarks>
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var patcher = new Patcher(state, Settings.Value);
            patcher.Run();
        }
    }
}
